All four exercise
kareraolivier/code-quality-exercise pull request #1
Opened 2023-10-19 08:45 UTC by kareraolivier

## Correction of exercises

2023-10-19 10:42 UTC, gsngdavid requested changes
Well done

2023-10-19 10:42 UTC, gsngdavid commented on exercisethree.js
Optional: put your if statements on one line since the body is made of single statement

2023-10-19 10:42 UTC, gsngdavid commented on exercisetwo.js
> +console.log(romanToNumber("VII"));
You can remove console after testing

2023-10-19 10:43 UTC, gsngdavid approved these changes

2023-10-20 08:20 UTC, kareraolivier commented on exercisethree.js
done

2023-10-20 08:20 UTC, kareraolivier commented on exercisetwo.js
> +console.log(romanToNumber("VII"));
removed

2024-01-04 13:42 UTC, merged